In [1]:
import numpy as np

In [6]:
x = np.array([[7,5,6],[5,2,9],[2,4,7]])
x

array([[7, 5, 6],
       [5, 2, 9],
       [2, 4, 7]])

In [7]:
np.linalg.eig(x)

(array([15.10882058,  3.55416175, -2.66298233]),
 array([[-0.68586066, -0.8728463 ,  0.27127735],
        [-0.57119158,  0.01626868, -0.90786732],
        [-0.45092719,  0.48772396,  0.31966472]]))

In [8]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
k = x + 45*e
np.linalg.eig(k)

(array([60.10882058, 48.55416175, 42.33701767]),
 array([[-0.68586066, -0.8728463 ,  0.27127735],
        [-0.57119158,  0.01626868, -0.90786732],
        [-0.45092719,  0.48772396,  0.31966472]]))

In [1]:
import samplecode

hello world
hi


In [4]:
samplecode.__name__

'samplecode'