In [1]:
import numpy as np

In [2]:
x = np.matrix([[8,4,2],[3,6,4],[8,7,3]])
x

matrix([[8, 4, 2],
        [3, 6, 4],
        [8, 7, 3]])

In [3]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
k = x + 45*e

In [5]:
np.linalg.eig(x)

(array([14.4449482 ,  3.40817447, -0.85312267]),
 matrix([[-0.52721625, -0.65831894,  0.04030168],
         [-0.50942159,  0.7527151 , -0.51678267],
         [-0.68009754,  0.00601265,  0.8551675 ]]))

In [6]:
np.linalg.eig(k)

(array([59.4449482 , 48.40817447, 44.14687733]),
 matrix([[-0.52721625, -0.65831894,  0.04030168],
         [-0.50942159,  0.7527151 , -0.51678267],
         [-0.68009754,  0.00601265,  0.8551675 ]]))